Close #11
qelphybox/hakeshonassybot pull request #128
Opened 2020-10-18 14:41 UTC by Johnny32id

Close https://github.com/qelphybox/hakeshonassybot/issues/11

Изменения предложенные в пул реквесте:
- Добавлена ачивка "философ чата" (с тестами)

@qelphybox @svyborov посмотрите, пожалуйста

2020-10-18 20:52 UTC, svyborov requested changes
Необходимо еще добавить тесты в файл actions.test.js по аналогии с остальными.

2020-10-18 20:52 UTC, svyborov commented on src/statistics/chatPhilosopher.js
> +    const filteredDataByTopMedian = data.filter((col) => col.median === topMedian);
Пробовал перенести это в запрос?

2020-10-19 17:57 UTC, Johnny32id commented
Добавил тесты в actions, переименовал опечатки, в запрос перенести не получилось, может в будущем придумаю как это сделать.

2020-10-19 18:32 UTC, svyborov approved these changes

2020-10-20 09:33 UTC, qelphybox reviewed
Круто! :+1:  Спасибо за реквест. Одна просьба и вопросик есть :smiley_cat:

2020-10-20 09:33 UTC, qelphybox commented on __tests__/actions.test.js
> +    const slimbot = createMockedSlimbot((chatId, text) => {
Я бы сделал эти тесты более наглядными, вроде такого:
```js
[14,14,14,14,14,3,3,3,3].forEach((messageLength, i) => {
    await sendTestMessage({
      userId: 2, firstName: 'user2', date: 1591790400 + i, type: 'text',
    }, onMessage, slimbot, 'a'.repeat(messageLength));
});

[14,14,14,14,14,3,3,3,3].forEach((messageLength, i) => {
    await sendTestMessage({
      userId: 1, firstName: 'user1', date: 1591790400 + i, type: 'text',
    }, onMessage, slimbot, 'a'.repeat(messageLength));
});
```

2020-10-20 09:33 UTC, qelphybox commented on __tests__/chatPhilosopher.test.js
> +const chatPhilosopher = require('../src/statistics/chatPhilosopher');
Для чего тесты в этом файле нужны? Они для удобства? Немного смущает что их читать сложно, но если вам с ними проще тестить функционал, я не против совсем, мне action тестов хватает.

2020-10-20 10:00 UTC, Johnny32id commented
Переделаю тесты.

2020-10-20 13:42 UTC, Johnny32id commented
Переделал тесты, как ты попросил @qelphybox

2020-10-20 13:56 UTC, qelphybox commented
@Johnny32id отлично выглядит, спасибо! Мерджим

2020-10-20 13:57 UTC, merged