#28 add onMessageEdit action
qelphybox/hakeshonassybot pull request #130
Opened 2020-10-18 21:49 UTC by svyborov

Close #28

Изменения предложенные в пул реквесте:
1. Добавлена реакция на изменение сообщения
2. Добавлены тесты на новый action

@qelphybox посмотри, пожалуйста

2020-10-20 14:42 UTC, qelphybox requested changes
@svyborov хорошая фича, спасибо! Одна небольшая правка

2020-10-20 14:42 UTC, qelphybox commented on __tests__/actions.test.js
> +  test('workless user', async () => {
```suggestion
  test('updates message in collection', async () => {
```

2020-10-20 18:15 UTC, qelphybox reviewed
@svyborov конфликты есть тут

2020-10-22 14:47 UTC, qelphybox commented
@svyborov снова конфликты :(

2020-10-22 19:23 UTC, svyborov commented
@qelphybox Ебанарот

2020-10-23 15:46 UTC, svyborov commented
@qelphybox Поправил

2020-10-26 09:17 UTC, qelphybox approved these changes
Круто, спасибо!

2020-10-26 09:17 UTC, merged