Уборка тестов
qelphybox/hakeshonassybot pull request #133
Opened 2020-10-20 16:18 UTC by Johnny32id

Close https://github.com/qelphybox/hakeshonassybot/issues/132

Изменения предложенные в пул реквесте:
-Раскидал action тесты на несколько тестов в зависимости от функционала.

@qelphybox @svyborov посмотрите, пожалуйста

2020-10-20 17:27 UTC, qelphybox commented
@Johnny32id тут конфликты надо разрезолвить

2020-10-20 18:37 UTC, Johnny32id commented
Вроде разрезолвил правильно @qelphybox

2020-10-20 18:39 UTC, qelphybox commented
@svyborov сделай ревью, пожалуйста

2020-10-21 20:07 UTC, svyborov requested changes

2020-10-21 20:07 UTC, svyborov commented on __tests__/contentSupplier.test.js
> +const createMockedSlimbot = (sendMessageFn) => ({ sendMessage: jest.fn(sendMessageFn) });
Функция в каждом файле дублируется, я думаю лучше вынести ее в отдельный файл. Например в sendMessageHelper.js

2020-10-22 13:38 UTC, Johnny32id commented
Вынес функцию в sendMessageHelper.js @svyborov проверь пожалуйста.

2020-10-22 13:42 UTC, svyborov requested changes

2020-10-22 13:42 UTC, svyborov commented on __tests__/chatPhilosopher.test.js
> +const createMockedSlimbot = (sendMessageFn) => ({ sendMessage: jest.fn(sendMessageFn) });
Тут ещё осталось функция.

2020-10-22 13:42 UTC, svyborov commented on __tests__/worklessUser.test.js
> +const createMockedSlimbot = (sendMessageFn) => ({ sendMessage: jest.fn(sendMessageFn) });
И тут

2020-10-22 13:43 UTC, Johnny32id commented on __tests__/worklessUser.test.js
> +const createMockedSlimbot = (sendMessageFn) => ({ sendMessage: jest.fn(sendMessageFn) });
Не заметил значит) Щас исправлю.

2020-10-22 13:43 UTC, svyborov commented
@Johnny32id В некоторый файлах функция осталась.

2020-10-22 13:46 UTC, Johnny32id commented
Исправил) @svyborov

2020-10-22 13:55 UTC, svyborov reviewed
2 require из одного файла, мб это и ок, я не уверен. Надо обсудить

2020-10-22 13:55 UTC, svyborov commented on __tests__/worstUser.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
2 require из одного файла

2020-10-22 13:55 UTC, svyborov commented on __tests__/worklessUser.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
2 require из одного файла

2020-10-22 13:55 UTC, svyborov commented on __tests__/stickerPacker.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
Тут тоже

2020-10-22 13:55 UTC, svyborov commented on __tests__/maybeDead.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
Тут тоже

2020-10-22 13:55 UTC, svyborov commented on __tests__/hours.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
Тут тоже

2020-10-22 13:55 UTC, svyborov commented on __tests__/dud.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
Тут тоже

2020-10-22 13:55 UTC, svyborov commented on __tests__/contentSupplier.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
Тут тоже

2020-10-22 13:55 UTC, svyborov commented on __tests__/chatPhilosopher.test.js
> +const { createMockedSlimbot } = require('./lib/sendMessageHelper');
Тут тоже

2020-10-22 14:03 UTC, Johnny32id commented
Передал) @svyborov

2020-10-22 14:10 UTC, svyborov approved these changes

2020-10-22 14:26 UTC, qelphybox approved these changes
Выглядит хорошо, спасибо всем! :love_you_gesture:

2020-10-22 14:26 UTC, merged